### ISSUE TITLE
Problemas con version nueva de Cube-Passport

### ISSUE THREAD

**Issue by akiot007** [cano-koa/cano-cube-passport#1]
Tengo problemas para poder compilar un proyecto ya que este me arroja el siguiente error:

(node:10869) UnhandledPromiseRejectionWarning: TypeError: options is not a function
    at map (/Users/akito/Documents/gateway/node_modules/cano-cube-passport/index.js:45:21)
    at /Users/akito/Documents/gateway/node_modules/lodash/_baseMap.js:17:23
    at /Users/akito/Documents/gateway/node_modules/lodash/_createBaseFor.js:17:11
    at baseForOwn (/Users/akito/Documents/gateway/node_modules/lodash/_baseForOwn.js:13:20)
    at /Users/akito/Documents/gateway/node_modules/lodash/_createBaseEach.js:17:14
    at baseMap (/Users/akito/Documents/gateway/node_modules/lodash/_baseMap.js:16:3)
    at map (/Users/akito/Documents/gateway/node_modules/lodash/map.js:50:10)
    at Promise (/Users/akito/Documents/gateway/node_modules/cano-cube-passport/index.js:42:13)
    at new Promise (<anonymous>)
    at PassportCube.up (/Users/akito/Documents/gateway/node_modules/cano-cube-passport/index.js:40:16)
(node:10869) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10869) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ernestojr** [comment]
Hola, gracias por avisar sobre del problema, en la próxima hora subiremos el fix.
